services:
  vue-frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "5173:5173"
    networks:
      - lalingua

  java-auth:
    build: .
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    environment:
      DB_HOST: db-mysql
      DB_NAME: auth
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8081:8080"
    networks:
      - lalingua

  db-mysql:
    image: mysql:8.4
    container_name: db-mysql
    #volumes:
      # Mount the root folder that contains .git
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lalingua
      MYSQL_PASSWORD: lalingua
      MYSQL_DATABASE: auth
    networks:
      - lalingua

networks:
  lalingua:
    driver: bridge
      