spring:
  application:
    name: 'demo'
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway: 
    enabled: true
jwt:
  access:
    issuer: ME
    key: MY_SECRET_KEY!
    expiration: 300
  refresh:
    expiration: 300
    length: 24
server:
 port: 8081
 ssl:
   key-store: classpath:keystore.p12
   key-store-password: test
   key-store-type: PKCS12
   key-alias: myalias
logging:
  level:
    org.springframework.web: "trace"
    org.springframework.security: "trace"
    org.hibernate: "debug"